# Generated by Django 5.0.2 on 2024-02-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
