# Generated by Django 5.0.2 on 2024-02-15 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_remove_advertisement_favorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteAdvertisement',
            new_name='Favorite_advertisements',
        ),
    ]
