# Generated by Django 5.0.1 on 2024-02-02 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='datetime_measure',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 12, 23, 37, 510428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=48),
        ),
    ]
