# Generated by Django 5.0.1 on 2024-02-02 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_datetime_measure_alter_sensor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensors',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='datetime_measure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
