# Generated by Django 5.0.1 on 2024-01-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
